server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: LuvIsLuvProject
  batch:
    job:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    schemas: ${MYSQL_DATABASE}
    clean-disabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: mongodb://localhost:27017/luvisluv

jwt:
  secretKey: HK6CKboFMIKurRejEK46GaVX9ev+F4v1tagcz64wOvlE/YJWy0KGu/87w4zQizP39muqL9UcYqdYH6Y268A+IQ==
  accessToken:
    time: 360000
  refreshToken:
    time: 8640000

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  server:
    port: 9292

# 카카오 API Key
kakao:
  api:
    key: ${KAKAO_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: luvisluv
    region:
      static: ap-northeast-2  # 서울 리전
    stack:
      auto: false