### 🙋‍♀️ [회원가입] 일반 유저 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "슬이",
  "email": "testv@example.com",
  "password": "TestPassword123!",
  "birthday": "1998-06-16",
  "userRole": "MANAGER"
}

###

### [로그인] access & refresh 토큰 발급
# 👉 로그인 후 응답 body에서 accessToken / refreshToken 복사해서 아래에 붙여넣기
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "testv@example.com",
  "password": "TestPassword123!"
}

###

### [로그아웃] accessToken 필요
POST http://localhost:8080/auth/logout
Authorization: Bearer {{accessToken}}

###

### [토큰 재발급] refreshToken 필요
GET http://localhost:8080/auth/refresh
Authorization: Bearer {{refreshToken}}

###
