### 1. 가게 등록 (MANAGER 권한 필요)
POST http://localhost:8080/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dkBleGFtcGxlLmNvbSIsInVzZXJSb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc1MDIzMzQ5MCwiZXhwIjoxNzUwMjMzODUwfQ.ALPb2dQhmrrqsGW7btaObNs2CfDWLUbm4fu2QCGs94k

{
  "name": "인생비빔밥2",
  "businessNumber": 1234567888,
  "contactNumber": "010-1233-5678",
  "address": "서울 구로구 디지털로27길 115",
  "status": "OPEN",
  "storeType": "CAFE"
}


### 2. 가게 수정 (MANAGER 권한 필요)
PUT http://localhost:8080/stores/1
Content-Type: application/json
Authorization: Bearer {{MANAGER_TOKEN}}

{
  "name": "이슬카페",
  "contactNumber": "010-9876-5432",
  "address": "서울특별시 마포구 와우산로 11길",
  "status": "CLOSED",
  "storeType": "CAFE"
}


### 3. 가게 삭제 (MANAGER 권한 필요)
DELETE http://localhost:8080/stores/1
Authorization: Bearer {{MANAGER_TOKEN}}


### 4. 내 주변 가게 조회 (권한 필요 없음)
GET http://localhost:8080/stores/nearby?lat=37.4848784332703&lng=126.8879955701&radius=2000
